allowed_pagy: 1
percentage: 100
avatar: "Avatar"

completion_rate:
  zero: 0

app:
  name: "Training System"
  version: "1.0.0"
  description: "A sample Ruby on Rails tutorial application"
  author: "Rails Tutorial"
  default_user_name: "User"

mailer:
  default_from: "noreply@example.com"

user:
  max_name_length: 50
  max_email_length: 255
  birthday_valid_years: 100
  min_password_length: 6
  roles:
    trainee: 0
    supervisor: 1
    admin: 2
  genders:
    female: 0
    male: 1
    other: 2
  status:
    active: 1
    inactive: 0
  status_label:
    active: "active"
    inactive: "inactive"
  birthday_format: "%d/%m/%Y"

course:
  max_name_length: 200
  creators: "creators"
  status:
    not_started: 0
    in_progress: 1
    finished: 2
  allowed_image_types: ["image/jpeg", "image/png"]
  max_image_size: 10 # in MB

subject:
  max_name_length: 150
  default_max_score: 100
  max_score_limit: 1000
  allowed_image_types: ["image/jpeg", "image/png"]
  max_image_size: 10 # in MB

category:
  max_name_length: 100

task:
  max_name_length: 200

comment:
  max_content_length: 5000
  min_content_length: 1

daily_report:
  min_content_length: 10
  max_content_length: 5000
  truncate_length: 100
  status:
    draft: 0
    submitted: 1
percentage: 100
user_task:
  min_spent_time: 0
  status:
    not_done: 0
    done: 1
  allowed_document_types: ["application/pdf", "image/jpeg", "image/png"]
  max_document_size: 50 # in MB
  spent_time_step: 0.1
  spent_time_min: 0

course_subject:
  min_position: 1

subject_category:
  min_position: 1

user_subject:
  min_score: 0
  max_score: 30
  status:
    not_started: 0
    in_progress: 1
    finished_early: 2
    finished_ontime: 3
    finished_but_overdue: 4
    overdue_and_not_finished: 5
  display_status:
    not_started: "not_started"
    in_progress: "in_progress"
    finished_early: "finished_early"
    finished_ontime: "finished_ontime"
    finished_but_overdue: "finished_but_overdue"
    overdue_and_not_finished: "overdue_and_not_finished"

user_course:
  status:
    not_started: 0
    in_progress: 1
    finished: 2
  status_label:
    not_started: "not_started"
    in_progress: "in_progress"
    finished: "finished"

validation_messages:
  required: "is required"
  too_long: "is too long"
  too_short: "is too short"
  invalid_format: "has invalid format"
  must_be_after: "must be after"
  must_be_greater_than: "must be greater than"
  cannot_exceed: "cannot exceed"

session:
  login_attempts_limit: 10
  lockout_duration: 900
  session_timeout: 7200

i18n:
  default_locale: "vi"
  available_locales: ["vi", "en"]
  fallback_locale: "vi"

email:
  from: "noreply@example.com"
  support: "support@example.com"

ui:
  theme: "default"
  items_per_page: 10
  max_upload_size: 5242880 # 5MB
  gravatar:
    default_size: 80
    list_size: 50
    small_size: 32

features:
  registration: true
  email_verification: false
  social_login: false

external_services:
  google_analytics: ""
  facebook_app_id: ""
  twitter_api_key: ""

links:
  help: "https://www.railstutorial.org/help"
  book: "https://www.railstutorial.org/book"
  railstutorial: "http://www.railstutorial.org/"
  gravatar: "https://secure.gravatar.com"
  gravatar_email: "http://gravatar.com/emails"

formats:
  date: "%d/%m/%Y"
  datetime: "%d/%m/%Y %H:%M:%S"
  decimal_places: 1

params:
  date: "%Y-%m-%d"

nil_value: "N/A"

pagination:
  default_per_page: 10
  course_members_per_page: 10
  max_per_page: 100
  min_pages_to_show: 1

page_classes:
  courses: "courses_page"
  admin_courses: "admin_courses_page"
  trainee_manager: "trainee-manager-page"
  supervisor_users: "supervisor-users-page"

scope:
  admin: "admin"
  supervisor: "supervisor"

templates:
  courses:
    members: "courses/members"
    subjects: "courses/subjects"

ui_limits:
  subject_tasks_preview_count: 3

defaults:
  count: 0

digits:
  digit_zero: 0
  digit_one: 1

subject_status:
  not_started: "not_started"
  in_progress: "in_progress"
  finished: "finished"
  min_estimated_time_days: 1
  subject_status_not_started: "not_started"
  zero: 0

cron:
  delete_drafts_interval_in_minutes: 1
  delete_drafts_interval_in_day: 1
  delete_time: "12:00 am"
image_user_default: "default_user_image.png"

trainee:
  subjects:
    min_tasks: 0
    default_progress: 0

views:
  supervisor:
    users:
      index:
        selected_count: "0"
      show:
        supervisors_display_limit: 2
