name: RuboCop Lint

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  rubocop:
    name: RuboCop Check
    runs-on: ubuntu-latest

    steps:
      # Lấy code từ repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Cài Ruby 3.2.2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true # Tự động cache gem

      # Cài đặt gem theo Gemfile (bundle install)
      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3

      # Chạy RuboCop với config chỉ định
      - name: Run RuboCop
        run: bundle exec rubocop --parallel --config .rubocop.yml
